# Generated by Django 2.2 on 2019-05-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
