# Generated by Django 2.2 on 2019-05-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
