# Generated by Django 2.2 on 2019-05-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
